import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const teg = Open_Sans({
  weight: ["400", "300", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${teg.className} max-w-screen`}>{children}</body>
    </html>
  );
}
